# Generated by Django 5.1.4 on 2026-03-31 21:42

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("library", "Library"),
                            ("bookstore", "Bookstore"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Admin-approved for institutional accounts.",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("institution_url", models.URLField(blank=True, null=True)),
                (
                    "full_name",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "address_line_1",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "address_line_2",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "AL"),
                            ("AZ", "AZ"),
                            ("AR", "AR"),
                            ("CA", "CA"),
                            ("CO", "CO"),
                            ("CT", "CT"),
                            ("DE", "DE"),
                            ("FL", "FL"),
                            ("GA", "GA"),
                            ("ID", "ID"),
                            ("IL", "IL"),
                            ("IN", "IN"),
                            ("IA", "IA"),
                            ("KS", "KS"),
                            ("KY", "KY"),
                            ("LA", "LA"),
                            ("ME", "ME"),
                            ("MD", "MD"),
                            ("MA", "MA"),
                            ("MI", "MI"),
                            ("MN", "MN"),
                            ("MS", "MS"),
                            ("MO", "MO"),
                            ("MT", "MT"),
                            ("NE", "NE"),
                            ("NV", "NV"),
                            ("NH", "NH"),
                            ("NJ", "NJ"),
                            ("NM", "NM"),
                            ("NY", "NY"),
                            ("NC", "NC"),
                            ("ND", "ND"),
                            ("OH", "OH"),
                            ("OK", "OK"),
                            ("OR", "OR"),
                            ("PA", "PA"),
                            ("RI", "RI"),
                            ("SC", "SC"),
                            ("SD", "SD"),
                            ("TN", "TN"),
                            ("TX", "TX"),
                            ("UT", "UT"),
                            ("VT", "VT"),
                            ("VA", "VA"),
                            ("WA", "WA"),
                            ("WV", "WV"),
                            ("WI", "WI"),
                            ("WY", "WY"),
                            ("DC", "DC"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                ("total_trades", models.PositiveIntegerField(default=0)),
                (
                    "avg_recent_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("inactivity_warned_1m", models.DateTimeField(blank=True, null=True)),
                ("inactivity_warned_2m", models.DateTimeField(blank=True, null=True)),
                ("books_delisted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active_at", models.DateTimeField(auto_now_add=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
