# Generated by Django 5.1.4 on 2026-05-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_institution_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution_bookshop_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
