# Generated by Django 5.1.4 on 2026-03-31 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("shipping_update", "Shipping Update"),
                            ("question", "Question"),
                            ("issue_report", "Issue Report"),
                            ("general_note", "General Note"),
                            ("delay_notice", "Delay Notice"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="trading.trade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Message",
                "verbose_name_plural": "Trade Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["trade", "created_at"],
                        name="messaging_t_trade_i_a74ae2_idx",
                    )
                ],
            },
        ),
    ]
