# Generated by Django 5.1.15 on 2026-04-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='trade_unique_source'),
        ),
    ]
