# Generated by Django 5.1.4 on 2026-03-31 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("ring", "Ring")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("proposed", "Proposed"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "indexes": [
                    models.Index(
                        fields=["status", "detected_at"],
                        name="matching_ma_status_63cb40_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchLeg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="matching.match",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_legs_as_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_legs_as_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_legs",
                        to="inventory.userbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Leg",
                "verbose_name_plural": "Match Legs",
                "indexes": [
                    models.Index(
                        fields=["sender", "status"],
                        name="matching_ma_sender__6fe918_idx",
                    ),
                    models.Index(
                        fields=["receiver", "status"],
                        name="matching_ma_receive_07f93c_idx",
                    ),
                ],
            },
        ),
    ]
