# Generated by Django 5.1.4 on 2026-03-31 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("traded", "Traded"),
                            ("donated", "Donated"),
                            ("removed", "Removed"),
                            ("delisted", "Delisted"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_listings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Book",
                "verbose_name_plural": "User Books",
                "indexes": [
                    models.Index(
                        fields=["user", "book", "status"],
                        name="inventory_u_user_id_9f2b35_idx",
                    ),
                    models.Index(
                        fields=["book", "status"], name="inventory_u_book_id_3015b0_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="inventory_u_status_de5ab1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "min_condition",
                    models.CharField(
                        choices=[
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                        ],
                        default="acceptable",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_entries",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
                "indexes": [
                    models.Index(
                        fields=["book", "is_active"],
                        name="inventory_w_book_id_c94136_idx",
                    )
                ],
                "unique_together": {("user", "book")},
            },
        ),
    ]
