# Generated by Django 5.1.4 on 2026-03-31 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "isbn_13",
                    models.CharField(db_index=True, max_length=13, unique=True),
                ),
                (
                    "isbn_10",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("authors", models.JSONField(default=list)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("publish_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "cover_image_cached",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("subjects", models.JSONField(default=list)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "open_library_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
    ]
