# Generated by Django 5.1.4 on 2026-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_physical_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
