# Generated by Django 5.1.4 on 2026-03-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_create_q_schedules"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_8a7c6b_idx",
            old_name="notificatio_user_id_is_read_idx",
        ),
    ]
